language: python 

dist: trusty
sudo: required

branches:
  only:
  - release # this buil just can be apply to branch

addons:
  sonarcloud:
    organization: $SONA_ORG_NAME # your organization name in sonarcloud
    token:
      secure: $SONAR_TOKEN # your sonar token encryoted by travos
jdk:
- oraclejdk8
script:
- sonar-scanner -X

cache:
  directories:
  - "$HOME/.sonar/cache"
