language: java
dist: trusty

branches:
  only:
  - release

addons:
  sonarcloud:
    organization: "nestor-mateus-globant" # the key of the org you chose at step #3
    token:
      secure: "3f31356b5f300d0d979ad5429cbb3382640431d5" # encrypted value of your token
    #code_climate:
      #repo_token: 9e5485644e68817249c41efc4ae4064ef45db50a

script:
  # other script steps might be done before running the actual analysis
  #- sonar-scanner
  - - sonar-scanner -Dsonar.projectKey=$PROYECT_KEY -Dsonar.sources=. -Dsonar.organization=nestor-mateus-globant


#jobs:
  #include:
    #- stage: "Run Tests & SonarCloud Analysis"
     # script:
      #  - sonar-scanner